app_bundle_content:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
    
login:
    pattern:   /login
    defaults:  { _controller: AppBundle:Security:login }

logout:
    pattern: /logout
    
login_check:
    pattern:   /login_check



