cms_auth_login:
    path:     /login
    defaults: { _controller: CmsAuthBundle:Auth:login }

cms_auth_login_check:
    path:     /login_check

cms_auth_home:
    path:     /
    defaults: { _controller: CmsAuthBundle:Auth:login }
