parameters:
#    cms_content.example.class: Cms\ContentBundle\Example

services:
#    cms_content.example:
#        class: %cms_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
