info_pengajian:
    resource: "@InfoPengajianBundle/Controller/"
    type:     annotation
    prefix:   /pengajian

learn:
    resource: "@LearnBundle/Controller/"
    type:     annotation
    prefix:   /
    

app_bundle:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
